### PR TITLE
Many improvements

### PR DESCRIPTION
**Pull request by darxriggs**
I suggest to review the individual commits as each covers a dedicated aspect and contains a detailed commit message.

### CODE REVIEW

**Comment by darxriggs** [comment]
@witokondoria ping

**Comment by darxriggs** [comment]
@witokondoria The merge conflict has been resolved now.

**Comment by darxriggs** [comment]
When this is merged, I have two other fixes in the queue. They currently would produce a merge conflict with this pull request.

**Comment by darxriggs** [comment]
@witokondoria ping

**Comment by darxriggs** [comment]
@witokondoria is there any chance to get this reviewed and merged?

**Comment by red8888** [comment]
@dalvizu the bitbucket aged-refs plugin is currently broken, does this fix that? But I think this project is dead?

**Comment by red8888** [comment]
whoops I spoke to soon looks like it is working now

**Comment by darxriggs** [comment]
@witokondoria can you have a look?

**Comment by askalski85** [comment]
Changes look cool, any chances to get this merged?

Question: is there any reason why the filter considers branches and PR's, and not tags? Or it just works for tags as well?

**Comment by askalski85** [comment]
I requested adding you to owners @darxriggs . @witokondoria please let me know if you disagree.
https://issues.jenkins.io/browse/INFRA-3134

**Comment by askalski85** [comment]
Ok @darxriggs we are unbblocked now. I will do some testing of the change and then we can merge it. Ill let you know in a few days.

**Comment by darxriggs** [comment]
@askalski85 Thank you for taking care of it.

**Comment by askalski85** [comment]
I had some issues testing this change locally. I will try to look closer in a following days.

**Review by askalski85 — APPROVED** [review]
Nice. I was able to finally test it locally. Thanks for awesome changes. Next step will be to update to java 11 and enable support for tags :-)

**Pull request merged**
