### PR TITLE
Add DataBoundConstructor annotation missing from Bitbucket plugin

### PR DESCRIPTION
**Pull request by ConstantineXVI**
Seemingly needed for Bitbucket plugin to function

### CODE REVIEW

**Comment by michelzanini** [comment]
Please merge this PR, as I think it probably fixes this issue:

screen shot 2018-07-06 at 14 02 49

**Comment by wrotte** [comment]
Is it possible to merge this PR?

**Comment by witokondoria** [comment]
I shamefully misses this Para. Sorry for the delay.

**Comment by wrotte** [comment]
@witokondoria thanks - would it be possible to cut a release with that fix included?

**Comment by witokondoria** [comment]
Will do so starting the next week (need a proper computar/connection)

**Comment by wrotte** [comment]
thanks!

**Comment by witokondoria** [comment]
0.2.0 released with this fix

**Pull request merged**
